'use strict';
const mongoose = require('mongoose');

const prodSchema = new mongoose.Schema({
    1850: { type: Number, required: true, default: 0},
    1851: { type: Number, required: true, default: 0},
    1852: { type: Number, required: true, default: 0},
    1853: { type: Number, required: true, default: 0},
    1854: { type: Number, required: true, default: 0},
    1855: { type: Number, required: true, default: 0},
    1856: { type: Number, required: true, default: 0},
    1857: { type: Number, required: true, default: 0},
    1858: { type: Number, required: true, default: 0},
    1859: { type: Number, required: true, default: 0},
    1860: { type: Number, required: true, default: 0},
    1861: { type: Number, required: true, default: 0},
    1862: { type: Number, required: true, default: 0},
    1863: { type: Number, required: true, default: 0},
    1864: { type: Number, required: true, default: 0},
    1865: { type: Number, required: true, default: 0},
    1866: { type: Number, required: true, default: 0},
    1867: { type: Number, required: true, default: 0},
    1868: { type: Number, required: true, default: 0},
    1869: { type: Number, required: true, default: 0},
    1870: { type: Number, required: true, default: 0},
    1871: { type: Number, required: true, default: 0},
    1872: { type: Number, required: true, default: 0},
    1873: { type: Number, required: true, default: 0},
    1874: { type: Number, required: true, default: 0},
    1875: { type: Number, required: true, default: 0},
    1876: { type: Number, required: true, default: 0},
    1877: { type: Number, required: true, default: 0},
    1878: { type: Number, required: true, default: 0},
    1879: { type: Number, required: true, default: 0},
    1880: { type: Number, required: true, default: 0},
    1881: { type: Number, required: true, default: 0},
    1882: { type: Number, required: true, default: 0},
    1883: { type: Number, required: true, default: 0},
    1884: { type: Number, required: true, default: 0},
    1885: { type: Number, required: true, default: 0},
    1886: { type: Number, required: true, default: 0},
    1887: { type: Number, required: true, default: 0},
    1888: { type: Number, required: true, default: 0},
    1889: { type: Number, required: true, default: 0},
    1890: { type: Number, required: true, default: 0},
    1891: { type: Number, required: true, default: 0},
    1892: { type: Number, required: true, default: 0},
    1893: { type: Number, required: true, default: 0},
    1894: { type: Number, required: true, default: 0},
    1895: { type: Number, required: true, default: 0},
    1896: { type: Number, required: true, default: 0},
    1897: { type: Number, required: true, default: 0},
    1898: { type: Number, required: true, default: 0},
    1899: { type: Number, required: true, default: 0},
    1900: { type: Number, required: true, default: 0},
    1901: { type: Number, required: true, default: 0},
    1902: { type: Number, required: true, default: 0},
    1903: { type: Number, required: true, default: 0},
    1904: { type: Number, required: true, default: 0},
    1905: { type: Number, required: true, default: 0},
    1906: { type: Number, required: true, default: 0},
    1907: { type: Number, required: true, default: 0},
    1908: { type: Number, required: true, default: 0},
    1909: { type: Number, required: true, default: 0},
    1910: { type: Number, required: true, default: 0},
    1911: { type: Number, required: true, default: 0},
    1912: { type: Number, required: true, default: 0},
    1913: { type: Number, required: true, default: 0},
    1914: { type: Number, required: true, default: 0},
    1915: { type: Number, required: true, default: 0},
    1916: { type: Number, required: true, default: 0},
    1917: { type: Number, required: true, default: 0},
    1918: { type: Number, required: true, default: 0},
    1919: { type: Number, required: true, default: 0},
    1920: { type: Number, required: true, default: 0},
    1921: { type: Number, required: true, default: 0},
    1922: { type: Number, required: true, default: 0},
    1923: { type: Number, required: true, default: 0},
    1924: { type: Number, required: true, default: 0},
    1925: { type: Number, required: true, default: 0},
    1926: { type: Number, required: true, default: 0},
    1927: { type: Number, required: true, default: 0},
    1928: { type: Number, required: true, default: 0},
    1929: { type: Number, required: true, default: 0},
    1930: { type: Number, required: true, default: 0},
    1931: { type: Number, required: true, default: 0},
    1932: { type: Number, required: true, default: 0},
    1933: { type: Number, required: true, default: 0},
    1934: { type: Number, required: true, default: 0},
    1935: { type: Number, required: true, default: 0},
    1936: { type: Number, required: true, default: 0},
    1937: { type: Number, required: true, default: 0},
    1938: { type: Number, required: true, default: 0},
    1939: { type: Number, required: true, default: 0},
    1940: { type: Number, required: true, default: 0},
    1941: { type: Number, required: true, default: 0},
    1942: { type: Number, required: true, default: 0},
    1943: { type: Number, required: true, default: 0},
    1944: { type: Number, required: true, default: 0},
    1945: { type: Number, required: true, default: 0},
    1946: { type: Number, required: true, default: 0},
    1947: { type: Number, required: true, default: 0},
    1948: { type: Number, required: true, default: 0},
    1949: { type: Number, required: true, default: 0},
    1950: { type: Number, required: true, default: 0},
    1951: { type: Number, required: true, default: 0},
    1952: { type: Number, required: true, default: 0},
    1953: { type: Number, required: true, default: 0},
    1954: { type: Number, required: true, default: 0},
    1955: { type: Number, required: true, default: 0},
    1956: { type: Number, required: true, default: 0},
    1957: { type: Number, required: true, default: 0},
    1958: { type: Number, required: true, default: 0},
    1959: { type: Number, required: true, default: 0},
    1960: { type: Number, required: true, default: 0},
    1961: { type: Number, required: true, default: 0},
    1962: { type: Number, required: true, default: 0},
    1963: { type: Number, required: true, default: 0},
    1964: { type: Number, required: true, default: 0},
    1965: { type: Number, required: true, default: 0},
    1966: { type: Number, required: true, default: 0},
    1967: { type: Number, required: true, default: 0},
    1968: { type: Number, required: true, default: 0},
    1969: { type: Number, required: true, default: 0},
    1970: { type: Number, required: true, default: 0},
    1971: { type: Number, required: true, default: 0},
    1972: { type: Number, required: true, default: 0},
    1973: { type: Number, required: true, default: 0},
    1974: { type: Number, required: true, default: 0},
    1975: { type: Number, required: true, default: 0},
    1976: { type: Number, required: true, default: 0},
    1977: { type: Number, required: true, default: 0},
    1978: { type: Number, required: true, default: 0},
    1979: { type: Number, required: true, default: 0},
    1980: { type: Number, required: true, default: 0},
    1981: { type: Number, required: true, default: 0},
    1982: { type: Number, required: true, default: 0},
    1983: { type: Number, required: true, default: 0},
    1984: { type: Number, required: true, default: 0},
    1985: { type: Number, required: true, default: 0},
    1986: { type: Number, required: true, default: 0},
    1987: { type: Number, required: true, default: 0},
    1988: { type: Number, required: true, default: 0},
    1989: { type: Number, required: true, default: 0},
    1990: { type: Number, required: true, default: 0},
    1991: { type: Number, required: true, default: 0},
    1992: { type: Number, required: true, default: 0},
    1993: { type: Number, required: true, default: 0},
    1994: { type: Number, required: true, default: 0},
    1995: { type: Number, required: true, default: 0},
    1996: { type: Number, required: true, default: 0},
    1997: { type: Number, required: true, default: 0 },
    1998: { type: Number, required: true, default: 0 },
    1999: { type: Number, required: true, default: 0 },
    2000: { type: Number, required: true, default: 0 },
    2001: { type: Number, required: true, default: 0 },
    2002: { type: Number, required: true, default: 0 },
    2003: { type: Number, required: true, default: 0 },
    2004: { type: Number, required: true, default: 0 },
    2005: { type: Number, required: true, default: 0 },
    2006: { type: Number, required: true, default: 0 },
    2007: { type: Number, required: true, default: 0 },
    2008: { type: Number, required: true, default: 0 },
    2009: { type: Number, required: true, default: 0 },
    2010: { type: Number, required: true, default: 0 },
    2011: { type: Number, required: true, default: 0 },
    2012: { type: Number, required: true, default: 0 },
    2013: { type: Number, required: true, default: 0 },
    2014: { type: Number, required: true, default: 0 },
    Country: { type: String, required: true },
    Sector: { type: String, required: true },
    parentSector: { type: String, required: false, default: ''}
  }, 
  {timestamps: true}
);

//recordSchema.index({ Country: 1 });

prodSchema.index({ Country: 1, type: -1 });

module.exports = mongoose.model('prodSchema', prodSchema);


